// Definición de campos y opciones de cada módulo.

export const OPT = {
  estadoPiso: [['interesante', 'Interesante'], ['visita_programada', 'Visita programada'], ['visitado', 'Visitado'],
    ['en_oferta', 'En oferta'], ['favorito', 'Favorito'], ['descartado', 'Descartado'], ['comprado', 'Comprado']],
  resultado: [['pendiente', 'Pendiente'], ['interesado', 'Interesado'], ['muy_interesado', 'Muy interesado'], ['no_interesado', 'No interesado']],
  via: [['agencia', 'Agencia'], ['directo', 'Directo'], ['portal', 'Portal inmobiliario'], ['conocido', 'Conocido'], ['otro', 'Otro']],
  financiacion: [['hipoteca', 'Hipoteca'], ['contado', 'Contado'], ['mixta', 'Mixta'], ['desconocida', 'Desconocida']],
  estadoOferta: [['recibida', 'Recibida'], ['contraofertada', 'Contraofertada'], ['aceptada', 'Aceptada'], ['rechazada', 'Rechazada'], ['retirada', 'Retirada']],
  tipoComision: [['porcentaje', 'Porcentaje sobre el precio'], ['importe_fijo', 'Importe fijo']],
  operacion: [['venta', 'Venta (casa de los padres)'], ['compra', 'Compra (casa nueva)']],
  estadoDoc: [['pendiente', 'Pendiente'], ['en_tramite', 'En trámite'], ['obtenido', 'Obtenido'], ['entregado', 'Entregado'], ['no_aplica', 'No aplica']],
  vivienda: [['actual', 'Casa actual (venta)'], ['nueva', 'Casa nueva']],
  tipoSum: [['luz', 'Luz'], ['gas', 'Gas'], ['agua', 'Agua'], ['internet', 'Internet'], ['movil', 'Móvil'], ['seguro_hogar', 'Seguro de hogar'],
    ['alarma', 'Alarma'], ['comunidad', 'Comunidad'], ['otro', 'Otro']],
  estadoSum: [['activo', 'Activo'], ['pendiente_cambio_titular', 'Pendiente cambio de titular'], ['pendiente_baja', 'Pendiente de baja'],
    ['de_baja', 'De baja'], ['pendiente_alta', 'Pendiente de alta']],
  categoria: [['cocina', 'Cocina'], ['bano', 'Baño'], ['electricidad', 'Electricidad'], ['fontaneria', 'Fontanería'], ['pintura', 'Pintura'],
    ['suelos', 'Suelos'], ['carpinteria', 'Carpintería'], ['ventanas', 'Ventanas'], ['climatizacion', 'Climatización'], ['otro', 'Otro']],
  prioridad: [['urgente', 'Urgente'], ['necesaria', 'Necesaria'], ['opcional', 'Opcional']],
  estadoRef: [['pendiente_presupuesto', 'Pendiente de presupuesto'], ['presupuestada', 'Presupuestada'], ['aprobada', 'Aprobada'],
    ['en_ejecucion', 'En ejecución'], ['finalizada', 'Finalizada']],
  tipoEvento: [['notaria', 'Notaría'], ['banco', 'Banco'], ['tasacion', 'Tasación'], ['mudanza', 'Mudanza'], ['reunion', 'Reunión'], ['otro', 'Otro']],
  categoriaTarea: [['fiscal', 'Fiscal'], ['mudanza', 'Mudanza'], ['notaria', 'Notaría'], ['general', 'General']],
};

export const TONO = {
  interesante: 'info', visita_programada: 'warn', visitado: 'neutral', en_oferta: 'accent', favorito: 'ok', descartado: 'muted', comprado: 'ok',
  pendiente: 'warn', interesado: 'info', muy_interesado: 'ok', no_interesado: 'muted',
  recibida: 'info', contraofertada: 'warn', aceptada: 'ok', rechazada: 'muted', retirada: 'muted',
  en_tramite: 'info', obtenido: 'ok', entregado: 'ok', no_aplica: 'muted',
  activo: 'ok', pendiente_cambio_titular: 'warn', pendiente_baja: 'warn', de_baja: 'muted', pendiente_alta: 'warn',
  urgente: 'danger', necesaria: 'warn', opcional: 'neutral',
};

export const F = {
  pisos: [
    { k: 'direccion', label: 'Dirección', req: true, full: true, placeholder: 'Calle, número, piso' },
    { k: 'municipio', label: 'Municipio', def: 'Majadahonda' },
    { k: 'barrio', label: 'Barrio / zona' },
    { k: 'precio_pedido', label: 'Precio pedido', type: 'money' },
    { k: 'precio_oferta', label: 'Nuestra oferta', type: 'money' },
    { k: 'metros', label: 'Superficie (m²)', type: 'number' },
    { k: 'habitaciones', label: 'Habitaciones', type: 'number', min: 0 },
    { k: 'banos', label: 'Baños', type: 'number', min: 0 },
    { k: 'planta', label: 'Planta' },
    { k: 'anio_construccion', label: 'Año de construcción', type: 'number' },
    { k: 'certificado_energetico', label: 'Certificado energético', placeholder: 'A–G' },
    { k: 'gastos_comunidad', label: 'Comunidad (€/mes)', type: 'money' },
    { k: 'ibi_anual', label: 'IBI (€/año)', type: 'money' },
    { k: 'ascensor', label: 'Ascensor', type: 'bool' },
    { k: 'garaje', label: 'Garaje', type: 'bool' },
    { k: 'trastero', label: 'Trastero', type: 'bool' },
    { k: 'terraza', label: 'Terraza', type: 'bool' },
    { k: 'obra_nueva', label: 'Obra nueva (IVA + AJD)', type: 'bool' },
    { k: 'estado', label: 'Estado', type: 'select', opts: OPT.estadoPiso, req: true, def: 'interesante' },
    { k: 'valoracion', label: 'Valoración', type: 'rating' },
    { k: 'fecha_visita', label: 'Próxima visita', type: 'date' },
    { k: 'hora_visita', label: 'Hora', type: 'time' },
    { k: 'contacto_nombre', label: 'Contacto' },
    { k: 'contacto_telefono', label: 'Teléfono', type: 'tel' },
    { k: 'contacto_agencia', label: 'Agencia / particular' },
    { k: 'enlace_anuncio', label: 'Enlace al anuncio', type: 'url', full: true, placeholder: 'https://' },
    { k: 'pros', label: 'Lo mejor', type: 'textarea' },
    { k: 'contras', label: 'Lo peor', type: 'textarea' },
    { k: 'notas', label: 'Notas', type: 'textarea' },
  ],
  visitas_pisos: [
    { k: 'fecha', label: 'Fecha', type: 'date', req: true },
    { k: 'hora', label: 'Hora', type: 'time' },
    { k: 'asistentes', label: 'Quién fue', full: true },
    { k: 'impresiones', label: 'Impresiones', type: 'textarea' },
  ],
  compradores: [
    { k: 'nombre', label: 'Nombre', req: true },
    { k: 'telefono', label: 'Teléfono', type: 'tel' },
    { k: 'email', label: 'Email', type: 'email' },
    { k: 'via', label: 'Cómo llegó', type: 'select', opts: OPT.via, def: 'agencia' },
    { k: 'fecha_visita', label: 'Fecha de visita', type: 'date' },
    { k: 'hora_visita', label: 'Hora', type: 'time' },
    { k: 'resultado', label: 'Resultado', type: 'select', opts: OPT.resultado, req: true, def: 'pendiente' },
    { k: 'notas', label: 'Notas', type: 'textarea' },
  ],
  ofertas: [
    { k: 'importe', label: 'Importe ofrecido', type: 'money', req: true },
    { k: 'fecha', label: 'Fecha', type: 'date', req: true },
    { k: 'financiacion', label: 'Financiación', type: 'select', opts: OPT.financiacion, def: 'hipoteca' },
    { k: 'estado', label: 'Estado', type: 'select', opts: OPT.estadoOferta, req: true, def: 'recibida' },
    { k: 'condiciones', label: 'Condiciones', type: 'textarea' },
  ],
  agencias: [
    { k: 'nombre', label: 'Agencia', req: true },
    { k: 'agente', label: 'Agente' },
    { k: 'telefono', label: 'Teléfono', type: 'tel' },
    { k: 'email', label: 'Email', type: 'email' },
    { k: 'tipo_comision', label: 'Tipo de comisión', type: 'select', opts: OPT.tipoComision, req: true, def: 'porcentaje' },
    { k: 'comision_valor', label: 'Comisión (% o €)', type: 'number', help: 'Ej.: 3 (si es %) o 9000 (si es fijo)' },
    { k: 'iva_incluido', label: 'La comisión ya incluye IVA', type: 'bool' },
    { k: 'exclusividad', label: 'Contrato en exclusiva', type: 'bool' },
    { k: 'fecha_firma', label: 'Fecha de firma', type: 'date' },
    { k: 'fecha_vencimiento', label: 'Vencimiento', type: 'date' },
    { k: 'prorroga_automatica', label: 'Prórroga automática', type: 'bool' },
    { k: 'dias_preaviso', label: 'Días de preaviso para cancelar', type: 'number', def: 15 },
    { k: 'clausulas', label: 'Cláusulas relevantes', type: 'textarea' },
    { k: 'notas', label: 'Notas', type: 'textarea' },
  ],
  documentos: [
    { k: 'nombre', label: 'Documento', req: true, full: true },
    { k: 'operacion', label: 'Operación', type: 'select', opts: OPT.operacion, req: true, def: 'venta' },
    { k: 'estado', label: 'Estado', type: 'select', opts: OPT.estadoDoc, req: true, def: 'pendiente' },
    { k: 'responsable', label: 'Quién lo consigue' },
    { k: 'fecha_caducidad', label: 'Caduca el', type: 'date' },
    { k: 'obligatorio', label: 'Obligatorio', type: 'bool', def: true },
    { k: 'descripcion', label: 'Descripción', type: 'textarea' },
    { k: 'notas', label: 'Notas', type: 'textarea' },
  ],
  suministros: [
    { k: 'vivienda', label: 'Vivienda', type: 'select', opts: OPT.vivienda, req: true, def: 'actual' },
    { k: 'tipo', label: 'Tipo', type: 'select', opts: OPT.tipoSum, req: true, def: 'luz' },
    { k: 'compania', label: 'Compañía' },
    { k: 'titular', label: 'Titular' },
    { k: 'numero_contrato', label: 'Nº de contrato' },
    { k: 'cups_referencia', label: 'CUPS / referencia' },
    { k: 'iban', label: 'Cuenta domiciliada (IBAN)' },
    { k: 'importe_mensual', label: 'Importe mensual', type: 'money' },
    { k: 'fecha_alta', label: 'Fecha de alta', type: 'date' },
    { k: 'fecha_vencimiento', label: 'Fin de permanencia', type: 'date' },
    { k: 'telefono_atencion', label: 'Teléfono de atención', type: 'tel' },
    { k: 'estado', label: 'Estado', type: 'select', opts: OPT.estadoSum, req: true, def: 'activo' },
    { k: 'fecha_accion', label: 'Fecha prevista del cambio', type: 'date' },
    { k: 'lectura_entrega', label: 'Lectura del contador en la entrega' },
    { k: 'notas', label: 'Notas', type: 'textarea' },
  ],
  reformas: [
    { k: 'titulo', label: 'Reforma', req: true, full: true, placeholder: 'Ej.: Cambiar bañera por plato de ducha' },
    { k: 'categoria', label: 'Categoría', type: 'select', opts: OPT.categoria, req: true, def: 'otro' },
    { k: 'estancia', label: 'Estancia' },
    { k: 'prioridad', label: 'Prioridad', type: 'select', opts: OPT.prioridad, req: true, def: 'necesaria' },
    { k: 'estado', label: 'Estado', type: 'select', opts: OPT.estadoRef, req: true, def: 'pendiente_presupuesto' },
    { k: 'presupuesto_estimado', label: 'Presupuesto estimado', type: 'money' },
    { k: 'pagado', label: 'Pagado hasta ahora', type: 'money' },
    { k: 'fecha_inicio', label: 'Inicio previsto', type: 'date' },
    { k: 'fecha_fin', label: 'Fin previsto', type: 'date' },
    { k: 'descripcion', label: 'Descripción', type: 'textarea' },
    { k: 'notas', label: 'Notas', type: 'textarea' },
  ],
  presupuestos: [
    { k: 'empresa', label: 'Empresa', req: true },
    { k: 'contacto', label: 'Contacto' },
    { k: 'telefono', label: 'Teléfono', type: 'tel' },
    { k: 'importe', label: 'Importe', type: 'money' },
    { k: 'fecha', label: 'Fecha', type: 'date' },
    { k: 'elegido', label: 'Presupuesto elegido', type: 'bool' },
    { k: 'notas', label: 'Notas', type: 'textarea' },
  ],
  tareas: [
    { k: 'titulo', label: 'Tarea', req: true, full: true },
    { k: 'categoria', label: 'Categoría', type: 'select', opts: OPT.categoriaTarea, req: true, def: 'general' },
    { k: 'fecha_limite', label: 'Fecha límite', type: 'date' },
    { k: 'hecha', label: 'Hecha', type: 'bool' },
    { k: 'notas', label: 'Notas', type: 'textarea' },
  ],
  eventos: [
    { k: 'titulo', label: 'Qué', req: true, full: true, placeholder: 'Ej.: Firma en notaría' },
    { k: 'tipo', label: 'Tipo', type: 'select', opts: OPT.tipoEvento, req: true, def: 'otro' },
    { k: 'fecha', label: 'Fecha', type: 'date', req: true },
    { k: 'hora', label: 'Hora', type: 'time' },
    { k: 'lugar', label: 'Lugar', full: true },
    { k: 'notas', label: 'Notas', type: 'textarea' },
  ],
  titulares: [
    { k: 'nombre', label: 'Nombre del titular', req: true, full: true },
    { k: 'porcentaje', label: '% de propiedad', type: 'percent', req: true, def: 50 },
    { k: 'fecha_nacimiento', label: 'Fecha de nacimiento', type: 'date', help: 'Para saber si tiene 65 años o más el día de la venta.' },
    { k: 'vivienda_habitual', label: 'Es su vivienda habitual', type: 'bool', def: true },
    { k: 'dependencia', label: 'Dependencia severa o gran dependencia', type: 'bool' },
    { k: 'notas', label: 'Notas', type: 'textarea' },
  ],
  operacion: [
    { k: 'direccion_venta', label: 'Dirección de la casa de los padres', full: true },
    { k: 'municipio_venta', label: 'Municipio (venta)' },
    { k: 'precio_venta_previsto', label: 'Precio de venta previsto', type: 'money' },
    { k: 'fecha_adquisicion', label: 'Fecha en que la compraron', type: 'date' },
    { k: 'precio_adquisicion', label: 'Precio de compra original', type: 'money' },
    { k: 'gastos_adquisicion', label: 'Gastos e impuestos de aquella compra', type: 'money' },
    { k: 'mejoras', label: 'Mejoras / reformas justificables', type: 'money' },
    { k: 'gastos_venta', label: 'Otros gastos de la venta', type: 'money', help: 'Sin contar la comisión de la agencia ni la plusvalía.' },
    { k: 'valor_catastral_total', label: 'Valor catastral total', type: 'money' },
    { k: 'valor_catastral_suelo', label: 'Valor catastral del suelo', type: 'money', help: 'Aparece en el recibo del IBI.' },
    { k: 'hipoteca_pendiente', label: 'Hipoteca pendiente', type: 'money' },
    { k: 'fecha_firma_venta', label: 'Fecha firma venta', type: 'date' },
    { k: 'notaria_venta', label: 'Notaría de la venta' },
    { k: 'municipio_compra', label: 'Municipio (compra)' },
    { k: 'precio_compra_previsto', label: 'Precio de compra previsto', type: 'money' },
    { k: 'compra_obra_nueva', label: 'La casa nueva es obra nueva', type: 'bool' },
    { k: 'fecha_firma_compra', label: 'Fecha firma compra', type: 'date' },
    { k: 'notaria_compra', label: 'Notaría de la compra' },
    { k: 'notas', label: 'Notas', type: 'textarea' },
  ],
};
